### ISSUE TITLE
valve的手柄信号问题

### ISSUE THREAD

**Issue by Neonbe** [Moon-Player/MoonVRVideoPlayer#13]
问题反馈：
2/ 新更新中断了Vive控制器和Oculus Quest控制器的支持，并阻止了从Steam启动器启动应用程序。

**分析：**
之前乱七八糟的兼容都是通过OPEN VR SDK实现的，我们应该是这些SDK除了问题

希望的达到的效果：支持手柄事件的输出，这里应该有
https://support.steampowered.com/kb_article.php?ref=1131-WSFG-3320#compathttps://github.com/ValveSoftware/openvr/wiki/API-Documentation
![image](https://user-images.githubusercontent.com/24536087/72624775-7d5d0000-3982-11ea-9f33-c112ae58414f.png)

**Comment by biezhihua** [comment]
目前已知的信息， Quest无法被SteamVR支持
