### ISSUE TITLE
#betarelease215 No2 播放页点击关闭屏幕镜像后，PC屏幕会一直闪……

### ISSUE THREAD

**Issue by Neonbe** [Moon-Player/MoonVRVideoPlayer#15]
问题：#必现 播放页，任意视频，点击左上角的关机屏幕镜像按钮，PC屏幕会一直闪一直闪……如群里视频

需要效果：点击屏幕后，桌面直接黑屏（黑色，不是息屏）

**Comment by biezhihua** [comment]
https://docs.unity3d.com/ScriptReference/XR.GameViewRenderMode.html 

https://docs.unity3d.com/ScriptReference/XR.GameViewRenderMode.html

API有问题，无法使用，先下线处理。
